adconda和jupyter notebook的安装
https://www.cnblogs.com/fwl8888/p/9586211.html

In [2]:
print('hello world!!!')

hello world!!!


使用print函数

In [3]:
print(100==200)

False


使用input函数

In [1]:
names = input()


Bob


In [2]:
names

'Bob'

python特性和变量名命名规则

#变量名可以是数字、字母和_的任意组合，但是不能以_作为开头
month  year2  1month  1_month   month_都是变量名
但是多个单词组合的时候，可以考虑使用下划线_连接，或者使用每个单词首字母大写的形式：如Split_Train_Test

python中的注释方法：
单行注释使用#
多行注释使用'''被注释掉的内容'''

In [7]:

print('hello')
print('world')
print('hi')

hello
world
hi


In [8]:
'''
print('hello')
print('world')
'''

print('hi')

hi


python中：的作用
1.在列表中[]，体现数据的切片

In [19]:
data = list(range(1,15,2))
data

[1, 3, 5, 7, 9, 11, 13]

In [20]:
data[:5] #表示取出列表中前5个元素

[1, 3, 5, 7, 9]

In [21]:
data[1:5]   #表示取出从第一位到第五位，其中[]左闭右开

[3, 5, 7, 9]

2.表示后续的缩进

In [24]:
for i in range(5):
    print(data[i])         #打印对应列表中元素
    print(i)               #打印i的循环（0-5）

1
0
3
1
5
2
7
3
9
4


dir和help的用法

In [25]:
print(help(dir))

Help on built-in function dir in module builtins:

dir(...)
    dir([object]) -> list of strings
    
    If called without an argument, return the names in the current scope.
    Else, return an alphabetized list of names comprising (some of) the attributes
    of the given object, and of attributes reachable from it.
    If the object supplies a method named __dir__, it will be used; otherwise
    the default dir() logic is used and returns:
      for a module object: the module's attributes.
      for a class object:  its attributes, and recursively the attributes
        of its bases.
      for any other object: its attributes, its class's attributes, and
        recursively the attributes of its class's base classes.

None


In [27]:
#dir(objiect)   #表示查询当前object的属性
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

import 的使用：表示导入相应的包，可直接使用相关功能

In [32]:
import numpy as np      #这里将numpy包引入，并使用了别名np,以后可以直接使用np.来调用相关函数
A = np.floor(10*np.random.random((3,3)))
print(A)

[[6. 3. 5.]
 [5. 3. 1.]
 [7. 8. 4.]]


pep8规范

    1 缩进与换行 每级缩进使用四个空格
    2 限制每行的最大长度为79个字符
    3 空行
        顶层函数和类之间使用两个空行
        类的方法之间用一个空行
        在函数中使用空行表示不同逻辑段落
    4 导入位于文件的顶部
    5 避免多余空格
    6 注释
        注释要保持与时俱进 一句后面两个空格 跟注释
    7 命名规范
        除了正常的命名规范外
        不要使用 大小写的L 大写的O 作为变量名
        类名首字母大写 内部类 加上前导下划线
        函数名应该小写 增强可读性可以使用下划线分割
    8 其他
        别用 ‘==‘ 进行布尔值 和 True 或者 False 的比较 应该用 is


In [39]:
a = 3    #a为int型
b = 9.0  #b为float型
a == b    #返回结果为bool型，只有TURE和False


False

In [40]:
a = 3    #a为int型
b = 3.0  #b为float型
a == b    #返回结果为bool型，只有TURE和False

True

In [41]:
c = a+ b
d = b/a
e = a*b
f = a-b
print(c)
print(d)
print(e)
print(f)

6.0
1.0
9.0
0.0


逻辑运算符包含 and or not   
成员运算符包含 in  not in
身份验证符包含 is  is not 


赋值运算符<逻辑运算符<关系运算符<算数运算符

算数运算符：+    -     *     /      %    **    //

逻辑运算符: and（逻辑与）    or （逻辑或）   not （逻辑非）

关系运算符:  <   <=   >   >=   != 

赋值运算符:=  %=  /=  //=  -=  +=  *=  **=